#http
version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/gdqreminder-by-vincent:latest
    restart: on-failure:5
    command:
      - --refreshIntervalInMS=60000
      - --seqHost=${SEQ_HOST}
      - --seqAPIKey=${SEQ_API_KEY}
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/firebase/firebase.json
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
      - SEQ_HOST=${SEQ_HOST}
      - SEQ_API_KEY=${SEQ_API_KEY}
    ports:
      - "3018:9000"
