#http
version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/gdqreminder-by-vincent:latest
    restart: on-failure:5
    command:
      - --refreshIntervalInMS=60000
      - --seqHost=${SEQ_HOST}
      - --seqAPIKey=${SEQ_API_KEY}
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/firebase/firebase.json
      - FIREBASE_JSON=${FIREBASE_JSON}
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
      - SEQ_HOST=${SEQ_HOST}
      - SEQ_API_KEY=${SEQ_API_KEY}

  nginx:
    image: nginx:alpine
    restart: on-failure:5
    ports:
      - "3018:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_cache:/var/cache/nginx/tracker
    depends_on:
      - app
    labels:
      prometheus.scrape: "true"
      prometheus.port: "80"
    networks:
      - default
      - prometheus

volumes:
  nginx_cache:

networks:
  default:
  prometheus:
    external: true
    name: prometheus_internal
