name: Build and test

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['lts/*', 'latest']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
      with:
        fetch-depth: 2 

    - name: Set up Node.js ${{ matrix.node }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: npm ci

    - name: Run the tests
      run: npm test -- --coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v7
      if: ${{ matrix.node }} == 'lts/*'
      with:
          token: ${{ secrets.CODECOV_TOKEN }}

  dockerPush:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: read
      packages: write
      
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Log in to the Container registry
        uses: docker/login-action@c99871dec2022cc055c062a10cc1a1310835ceb4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  hetznerDeploy:
    runs-on: gdqreminder
    needs: [dockerPush]
    if: (github.ref == 'refs/heads/main' && github.event_name == 'push')
    steps:
      - name: Run refresh script
        run: refreshGDQReminder.ps1
